### ISSUE TITLE
Remove cache flusher (or implement a smarter one)

### ISSUE THREAD

**Issue by havogt** [GridTools/gridtools#1468]
once we have perftests validated after refactoring.

Try to remove and see implications.

**Comment by fthaler** [comment]
Just removing the cache flusher leads to huge performance differences between different perftest execution due to different addresses of the allocated data. Introducing multiple instances of data sets that are switched before each run partially addresses the issue, that is, gives large differences within the samples run in one execution of the perftests rather than only over different executions. But due to possible multi-modal and wider sample distributions, a much larger amount of samples per execution is needed to do statistically meaningful analysis. For those reason and currently low importance, the current behavior is kept for now.

**Comment by havogt** [comment]
closing as won't fix and not important enough to keep it open
