### ISSUE TITLE
[Question]- How to enabel girdtool for  COSMO model in  GPU ?

### ISSUE THREAD

**Issue by ashkildighin** [GridTools/gridtools#1573]
GridTools is successfully used to accelerate the dynamical core of the COSMO model 
 1.Is any build steps or procedure to accelerate the dynamical core of the COSMO  in GPU's like Nvidia/AMD?
 2. Is any specific version  COSMO Model or source code version. required 
 3. COSMO has different types of Packages/consortium, Is girdtool support for all packages?
   Example:http://cosmo-model.org/content/support/software/default.htm

**Comment by havogt** [comment]
GridTools-powered GPU support is available since COSMO v5.7, see http://cosmo-model.org/content/model/releases/histories/cosmo_5.07.htm. Previous versions were based on another library called STELLA. GPU support in COSMO is not 100%, meaning not all components are GPU capable, only the most relevant parts for NWP and climate groups interested in GPU (if I am not mistaken). Please contact the COSMO consortium for more detailed information.

COSMO v5.7 comes with build instructions for the GPU-enabled dynamical core (which is a re-implementation in C++ based on GridTools).

Nvidia GPUs are supported. The dynamical core should in principle work as well on AMD GPUs with modifications in the build system (this is not tested).
The non-dycore parts of COSMO for GPU are accelerated with OpenACC. I am not up to date with AMD support for OpenACC.

I'll close this issue. Feel free to re-open if you have more questions.
